apiVersion: v1
kind: Namespace
metadata:
  name: dev

---

apiVersion: v1
kind: LimitRange
metadata:
  name: default-cpu-mem-limit-range
  namespace: dev
spec:
  limits:
    - default:
        memory: "512Mi" # If not specified, the Container's memory limit is set to 512Mi, which is the default memory limit for the namespace. Mi here represents MebiBytes.
        cpu: "500m"  # 500m means 500 millicores or half a core. If not specified, default limit is 1 vCPU (core) per container 
      defaultRequest:
        memory: "256Mi" # If not specified, by default the container will take from whatever is specified in limits.default.memory
        cpu: "300m" # If not specified, default the container will take from whatever is specified in limits.default.cpu
      type: Container      


# Note that 1 t3.medium instance has 2 vCPUs and 4 GB memory. 
# 1 GB = ~954 Mebibytes. 
# So, in each worker node, out of a max of 2 vCPUs, we use a max of 0.5 vCPU (0.3 vCPU ideally) for 1 container.
# Also, in each worker node, out of a max of 3816 Mi. we use a max of 512 Mi (256 Mi ideally) for 1 container.


---

apiVersion: v1
kind: ResourceQuota
metadata:
  name: ns-resource-quota
  namespace: dev
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi  
    pods: "5"    
    configmaps: "5" 
    persistentvolumeclaims: "5" 
    replicationcontrollers: "5" 
    secrets: "5" 
    services: "5"     